### ISSUE TITLE
Opening the executable gives a blank cmd box.

### ISSUE THREAD

**Issue by KruzShady** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#24]
Just as the title says, when I open c-real.exe, a blank cmd box pops up.

1. Run c-real.exe

**Comment by TKperson** [comment]
Since the file name of the exe file is called c-real.exe -- I'm assuming you are using an older version

**Comment by TKperson** [comment]
This is the newest version so far: https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.2.5/c-realV2.zip

And you should be able to see c-realV2.exe instead of c-real.exe 
c-real.exe is version 0.7 it doesn't have any error detection, so it will only close itself when seeing an error

**Comment by KruzShady** [comment]
I downloaded that version, and it does the same thing. I extract everything, I run the c-realV2.exe, and then just a blank cmd box.

**Comment by TKperson** [comment]
hmm have you tried to wait for a few moments after starting up the exe file?

and if you have anti virus this might be caused by that.

**Comment by KruzShady** [comment]
Yup, it was my anti-virus. Looks like just excluding it didn't work.
