### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by stop-bark** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#57]
so mass dm, right so you cant get every member in a server, but you can get every member thats available in a channel, so example a welcome channel or something

idk how to really make it but heres a c# version https://github.com/not-ilinked/Anarchy/blob/8b9e43d240a5d34fe49641dc37da3affc4f5ef35/Anarchy/WebSockets/Gateway/Guild/Extensions.cs#L129
idk how to make it in python so yeah

**Comment by TKperson** [comment]
### For selfbots
Fetching/Getting members wasn't a problem. I'm not sure what that c# program did.

I have already tried 1 week a while ago: [fetch members](https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/blob/16f816a1438414e9e19173872bd02bc0676c805c/c-realV2.py#L660) and [massDM](https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/blob/16f816a1438414e9e19173872bd02bc0676c805c/c-realV2.py#L1256)

The problem was dm'ing the members
New users seems like they can only dm up to 3 other people
Recently (I tested dm'img people again) I realized there's a rate limit for how many people it can dm
since it is a rate limit then there must be a timer. So I set an interval to dm people every minute - it worked I could dm however many people with that account I wanted, but I'll have to wait 1 minute for each dm.

Maybe the dm rate limit can be lower; I have only tested a 40 seconds interval and a 60 seconds interval. Or there might be a different result for old users or verified accounts. Those are the things I still need to test.

**Comment by cyxl** [comment]
Yea, couldn't make up my mind. My bad
